### ISSUE TITLE
Error when using a Wasm App that is served from a different path than the root of the website

### ISSUE THREAD

**Issue by victorperez2911** [tpeczek/Blazor.BroadcastChannel#2]
First, Nice Lib, congrats

When used with a diff base address, request for Blazor.BroadcastChannel.js file fail with 404 http status code.

i Found this

https://github.com/dotnet/aspnetcore/issues/47627

**Comment by victorperez2911** [comment]
I made a PR, please validate.

#3

**Comment by tpeczek** [comment]
Hi @victorperez2911,

Thank you for the PR, I'll take a look 🙂.

**Comment by tpeczek** [comment]
Hi @victorperez2911,

I was about to push an alfa version for testing, but I've reached out to some people and done some more testing and it looks that change to the library may in fact not be the desired approach (although I don't have certainty at this point). So I wanted to ask if you can check if you have call to `UsePathBase` in your pipeline setup (it should be before `UseStaticFiles`)? If you don't, can you include it and check if it solves your issue?

**Comment by victorperez2911** [comment]
> Hi @victorperez2911,
> 
> I was about to push an alfa version for testing, but I've reached out to some people and done some more testing and it looks that change to the library may in fact not be the desired approach (although I don't have certainty at this point). So I wanted to ask if you can check if you have call to `UsePathBase` in your pipeline setup (it should be before `UseStaticFiles`)? If you don't, can you include it and check if it solves your issue?

Before making this change (<base href="/MyApp/"), I read the article below.

https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/?view=aspnetcore-8.0&tabs=visual-studio

And from what I read, the use of the command you suggested only occurs if wasm is hosted by an AspNet Core project, which is not my case.

In my case, it is a Blazor Web Assembly application, which will be served by a Web server, on a Static Web Site.

And for this, just changing the href attribute of the base element is enough.

https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/?view=aspnetcore-5.0&tabs=netcore-cli#standalone-blazor-webassembly

Although.

I found an approach in the documentation that makes it possible to test this scenario (setting a base path different from the web site's root) in the development environment.

I'll do one more test (with "./_content/") and post the results here.

**Comment by victorperez2911** [comment]
Hi @tpeczek 

I did the tests with the suggested url (with prefix "./") and everything worked correctly, both in dev, using the value of the href attribute of the base element with value "/" (which is the default value), as well in Web Server as with " /MyApp/" (just as the official Microsoft article suggests).

I updated the PR with the correction.

**Comment by tpeczek** [comment]
@victorperez2911 I've reviewed, merged, and released it 😊
